### ISSUE TITLE
Support for USFM 3.0 ?

### ISSUE THREAD

**Issue by DavidHaslam** [kahunapule/haiola#1]
[USFM 3.0](https://ubsicap.github.io/usfm/about/releasenotes.html) is on its way.

Bible software developers should plan to support the new markers, revised markers, and the features and syntax improvements.

The new version is currently **3.0rc1** prerelease stage.
I expect it will be released at the same time as **ParaTExt 8.0** during 2017.

**Comment by DavidHaslam** [comment]
See similar issue in [refdoc / Module-tools](https://github.com/refdoc/Module-tools/issues/1) along with my comments.

**Comment by kahunapule** [comment]
I'm implementing support for USFM 3.0 \fig and \w tags, now.

**Comment by DavidHaslam** [comment]
Is the implementation complete yet?

**Comment by kahunapule** [comment]
I thought it was until a few days ago when I found a difference in the way Paratext implemented part of it. Paratext is not yet complete in this, so my support of USFM 3.0 with respect to word level markup is subject to adjustment at least one more time.

Aloha,
Michael
http://mpj.us

**Comment by br8kpoint** [comment]
So it's now 8 months since the last comment and 3.0 is in RC. So has word level markup been implemented?

**Comment by kahunapule** [comment]
On 08/29/2018 01:10 PM, Mike Fair wrote:
>
> So it's now 8 months since the last comment and 3.0 is in RC. So has word level markup been implemented?
>

It has been implemented in Haiola (which I mostly maintain), and partially implemented in Paratext (which I don't maintain).

-- 
signature

Aloha,
*/Michael Johnson/**
PO BOX 881143 • PUKALANI HI 96788-1143*• USA
mljohnson.org <http://mljohnson.org> • Phone: +1 808-333-6921 • Skype: kahunapule

**Comment by kahunapule** [comment]
USFM 3 has turned into a moving target. Implementation of all that is used "in the wild" is done. Some parts of USFM 3 may never be supported by Haiola, as they aren't relevant to Haiola's main mission and function.
